In [1]:
import torch

In [29]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.biases = bias

    def __call__(self, x):
        return torch.sigmoid((x @ self.weights.T   + self.biases.T))

In [33]:
x = torch.tensor([[0.2, 0.3],
                  [0.1, 0.2],
                  [0.3, 0.2]])
y = torch.tensor([[0],
                  [1],
                  [1]])
weights = torch.tensor([[1., 1.]])
bias = torch.tensor([[0.]])

In [34]:
net = Neuron(weights=weights, bias=bias)
pred = net(x)

In [35]:
pred

tensor([[0.6225],
        [0.5744],
        [0.6225]])

In [40]:
pred.shape

torch.Size([3, 1])

In [41]:
y.shape

torch.Size([3, 1])

In [46]:
def nll_loss(y_pred, y_true):
    return -1 * (y_true * torch.log(y_pred) + (1 - y_true) *
             torch.log(1 - y_pred))

nll_loss(pred, y)

tensor([[0.9741],
        [0.5544],
        [0.4741]])

In [43]:
-(y * torch.log(pred))

tensor([[0.0000],
        [0.5544],
        [0.4741]])

In [44]:
()

tensor([[-0.9741],
        [-0.0000],
        [-0.0000]])

In [45]:
-(y * torch.log(pred) + (1 - y) * torch.log(1 - pred))

tensor([[0.9741],
        [0.5544],
        [0.4741]])

In [52]:
y

tensor([[0],
        [1],
        [1]])

In [58]:
loss_torch = torch.nn.NLLLoss()
preds = torch.nn.functional.log_softmax(torch.tensor([[0.6, 0.2],
                  [0.1, 0.2],
                  [0.3, 0.8]]), dim=1)
print(preds)
loss_torch(preds, y.squeeze())

tensor([[-0.5130, -0.9130],
        [-0.7444, -0.6444],
        [-0.9741, -0.4741]])


tensor(0.5438)

In [54]:
y.shape

torch.Size([3, 1])